version: 2
orbs:
  python: circleci/python@0.2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8
    environment:
      ENV: config/local/.env
    steps:
      - checkout
      - run:
          name: "Check Environment of Project"
          command: |
            echo $PYPI_USERNAME
            echo $PYPI_PASSWORD
      - run:
          name: Publishing wheel to PyPi
          command: |
            set -e
            mkdir /home/circleci/.pip     
            export ENV=local
             
            pip config list -v
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install --upgrade twine

            bash -c "python3 setup.py bdist_wheel && python3 -m twine upload dist/* --username=$PYPI_USERNAME --password="$PYPI_PASSWORD"