version: 2
orbs:
  python: circleci/python@0.2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.8     
    environment:
      ENV: config/local/.env
    steps:
      - checkout
      - run:
          name: "Check Environment of Project"
          command: |
            echo $PYPI_USERNAME
            echo $PYPI_PASSWORD
      - run:
          name: Publishing wheel to PyPi
          command: |
            python3 setup.py sdist bdist_wheel
            sudo add-apt-repository universe -y
            sudo apt-get update
            sudo apt install -y python3-pip
            sudo pip install pipenv
            pipenv install twine
            pipenv run twine upload dist/*
